export type Locale = "es" | "en"

export const portfolioCopy = {
  es: {
    home: "Inicio",
    projects: "Proyectos",
    stack: "Stack",
    experience: "Experiencia",
    about: "Acerca de",
    contact: "Contacto",
    goHome: "Ir al inicio",
    github: "Abrir GitHub",
    navigation: "Navegación principal",
    mobileNavigation: "Navegación móvil",
    skip: "Saltar al contenido",
    book: "Agendar reunión",
    bookShort: "Agendar",
    download: "Descargar CV",
    portrait: "Retrato de",
    professional: "Perfil profesional",
    available: "Disponible",
    menu: "Menú de navegación",
    years: "años",
    clients: "Clientes",
    recent: "Proyectos recientes",
    recentDescription: "Productos que he llevado de idea a producción.",
    technologies: "Stack tecnológico",
    technologiesDescription: "Herramientas elegidas según el problema.",
    dailyTools: "Tecnologías en el día a día",
    experienceDescription: "Productos, equipos y operaciones digitales.",
    aboutPhoto: "junto a un río, con una ciudad al fondo",
    aboutHeading: "Construyo productos completos, no piezas aisladas.",
    catalog: "Catálogo de proyectos",
    catalogDescription: "Una selección de plataformas, productos y sitios.",
    activity: "Actividad de GitHub",
  },
  en: {
    home: "Home",
    projects: "Projects",
    stack: "Stack",
    experience: "Experience",
    about: "About",
    contact: "Contact",
    goHome: "Go to home",
    github: "Open GitHub",
    navigation: "Main navigation",
    mobileNavigation: "Mobile navigation",
    skip: "Skip to content",
    book: "Book a meeting",
    bookShort: "Book",
    download: "Download CV",
    portrait: "Portrait of",
    professional: "Professional profile",
    available: "Available",
    menu: "Navigation menu",
    years: "years",
    clients: "Clients",
    recent: "Recent projects",
    recentDescription: "Products I have taken from idea to production.",
    technologies: "Technology stack",
    technologiesDescription: "Tools chosen to fit the problem.",
    dailyTools: "Everyday technologies",
    experienceDescription: "Products, teams, and digital operations.",
    aboutPhoto: "beside a river, with a city in the background",
    aboutHeading: "I build complete products, not isolated pieces.",
    catalog: "Project catalog",
    catalogDescription: "A selection of platforms, products, and websites.",
    activity: "GitHub activity",
  },
} as const
